### PR TITLE
Samplesheet check update script

### PR DESCRIPTION
**Pull request by alexiswl**
## Files added

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/env/samplesheet-check.yml)  

[Link](https://github.com/umccr/infrastructure/blob/0a6bc6fa45a9990b1f2a6f870ef6ad8c648d6f3b/scripts/umccr_pipeline/umccr_utils/errors.py)

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/umccr_utils/globals.py)

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/umccr_utils/google_lims.py)

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/umccr_utils/logger.py)

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/umccr_utils/samplesheet.py)

## Files Edited

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/samplesheet-check-gui-wrapper.py)

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/samplesheet-check.py)  

[Link](https://github.com/umccr/infrastructure/blob/36298f4ee417d45d2c4381f4e846c9fd420a1abc/scripts/umccr_pipeline/update-google-lims.py)

### Readme.md
Replaced vague installation steps with `conda env create --file /path/to/yml` instead

### CODE REVIEW

**Comment by alexiswl** [comment]
Moved to draft - exploring web-app option after dev meeting

**Comment by alexiswl** [comment]
## Draft updates:

* Updated column name for `IDT Index , unless stated` to `TruSeq Index, unless stated` (86ebcc8)
* Updated README for conda installation after tests on new computer (c288a61)
* Overwrite changes for collecting library sheets in (e95998c)

**Comment by brainstorm** [comment]
I guess this is deprecated by @williamputraintan's work?

**Comment by reisingerf** [comment]
I suppose it will be ....

**Comment by alexiswl** [comment]
Eventually yes. This is currently still what's on lab's desktop computers, main difference will be use of the LabMetadata objects over the GLims access. I think in most cases this is going to be pretty transferrable.

**Pull request closed without merging**
