### PR TITLE
Use alternative hash table paths for production workflows

### PR DESCRIPTION
**Pull request by alexiswl**
## TODO
- [x] Test out #165 on dataportal
- [x] https://github.com/umccr/cwl-ica/pull/15 is pulled and a workflow version exists on prod
- [x] We launch the workflow version generated in https://github.com/umccr/cwl-ica/pull/15 with the inputs described [here](https://github.com/umccr/workflows/blob/dragen-reference-update-3.7.5/DRAGEN_README.md#reference-hash-tables), and as shown [here](https://github.com/umccr/cwl-ica/blob/main/.github/catalogue/docs/tools/custom-create-umccr-dragen-refdata-tarball-from-illumina-tar/1.0.0/custom-create-umccr-dragen-refdata-tarball-from-illumina-tar__1.0.0.md#run-wfr3bf2bc688d0d442489cadfcdb2bf9842)

## Description
Mirror of #165 but for prod workflows

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]
LGTM

**Review by skanwal — APPROVED** [review]
LGTM as well.

**Comment by victorskl** [comment]
Otherwise LGTM!

I will hold off "Approve" for now to wait for TODO items and, the ref data bundle to be provisioned at the said locations in this PR (just checked and they are not there yet, at the mo). Pls kindly ping once you are up for the merge or, mark this PR to "Ready for review", Alexi.

**Comment by alexiswl** [comment]
> Otherwise LGTM!
> 
> I will hold off "Approve" for now to wait for TODO items and, the ref data bundle to be provisioned at the said locations in this PR (just checked and they are not there yet, at the mo). Pls kindly ping once you are up for the merge or, mark this PR to "Ready for review", Alexi.

@victorskl are you able to run this one? *Test out Updated to use illumina reference bundle for dev #165 on dataportal*, we just need to deploy a batch of `dragen_wgs_qc` and make sure they all run from start to finish.  

*We launch the workflow version generated in Added create dragen tarball to prod project cwl-ica#15 with the inputs described here, and as shown here*

@reisingerf this workflow is in the prod environment now under `wfl.925c7ba0199a4ad6bb5341a3cffd191d` version `1.0.0--a53aa79` as shown [here](https://github.com/umccr/cwl-ica/blob/main/.github/catalogue/docs/tools/custom-create-umccr-dragen-refdata-tarball-from-illumina-tar/1.0.0/custom-create-umccr-dragen-refdata-tarball-from-illumina-tar__1.0.0.md#project-production_workflows)

**Comment by victorskl** [comment]
> are you able to run this one? [...] make sure they all run from start to finish

@alexiswl Do you mean whether I can trigger some validation run for `dragen_wgs_qc` in DEV?

**Comment by alexiswl** [comment]
> @alexiswl Do you mean whether I can trigger some validation run for dragen_wgs_qc in DEV?

Yes, but also happy to wait for the next portal release to test this.

**Comment by victorskl** [comment]
Right, gotcha, will do. Yep, patch [release 0.4.1](https://github.com/umccr/data-portal-apis/milestone/3) is about to conclude soon. So, let go along with this release together for this ref data changes at workflow side.

**Comment by victorskl** [comment]
- Portal validation run for [Release 0.5.0](https://github.com/umccr/data-portal-apis/milestone/3?closed=1) with new DRAGEN ref hash table in DEV is passed; ticked the checkbox.
- Next, waiting for provisioning those ref hash table in this PR into PROD volume now. Once in, I will approve and, can apply it into PROD.

**Review by victorskl — APPROVED** [review]
Thkz all, applying to PROD along with Portal Release 0.5.0

**Pull request merged**
