### PR TITLE
Update dev workflow ids for somatic and umccrise

### PR DESCRIPTION
**Pull request by alexiswl**
Dragen somatic now also calls germline tool

Runs germline in somatic step, not umccrise step

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM. Shall I apply it to dev straight away? Or have you applied it already?

**Comment by alexiswl** [comment]
> LGTM. Shall I apply it to dev straight away? Or have you applied it already?

No, please leave it for now, should have put it as a draft, have a data-portals-api pr to complement it.

**Review by victorskl — COMMENTED** [review]
@alexiswl On the closer look; this seem to have change input and output structure, quite a bit.

I peek into related upstream on somatic+germline workflow
https://github.com/umccr/cwl-ica/blob/main/.github/catalogue/docs/workflows/dragen-somatic-with-germline-pipeline/4.0.3/dragen-somatic-with-germline-pipeline__4.0.3.md

I reckon, are you still finalising/testing on 3.9.3 counterpart of tumor/normal workflow as well as umccrise?

And. There is still follow up on `wgs_tumor_normal` and `umccrise` input/output template JSON updates, correct?
https://github.com/umccr/infrastructure/tree/master/terraform/stacks/umccr_data_portal/workflow/template

**Review by victorskl — APPROVED** [review]
ditto https://github.com/umccr/data-portal-apis/pull/572#pullrequestreview-1329831541 Let get merged in and apply to DEV for trial T/N trigger from Dev Portal UI. Next.

**Comment by victorskl** [comment]
Merging... I will apply this to DEV; to test it through Portal UI T/N trigger as discussed. FYI

**Pull request merged**
