### PR TITLE
Upgrade prod RNAsum to 0.4.9

### PR DESCRIPTION
**Pull request by skanwal**
Linked cwl-ica PR https://github.com/umccr/cwl-ica/pull/386

### CODE REVIEW

**Comment by victorskl** [comment]
Checklist

* [ ] #352 must be merged and did run RNAsum pipeline automation in Portal Staging, first

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update BioInfo platform with RNAsum 0.4.8](https://trello.com/c/4x3cFDCE/1544-portal-release-ocicat-update-bioinfo-platform-with-rnasum-048)

**Comment by skanwal** [comment]
Upgrading to 0.4.9

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
I will be rebasing this onto latest master HEAD. Hence, force push to update the branch. And resolve the conflict.

**Review by victorskl — APPROVED** [review]
Assert that


Workflow version exists and equal to Staging 
```
ica workflows versions list wfl.87e07ae6b46645a181e04813de535216 | grep 0.4.9--3694eb2
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1698458855112429

**Review by reisingerf — APPROVED** [review]
LGTM
(Existence of workflow version in `production` verified)

**Review by ohofmann — COMMENTED** [review]
Also go!

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
