### PR TITLE
Updated production workflow of tso_ctdna

### PR DESCRIPTION
**Pull request by alexiswl**
## Changes

* Include multiqc step for AlignCollapseFusionCaller step
* Fail earlier in case of workflow step failing by examining dsdm jsons at the end of the initial subworkflow
* Coerce correct index for samples with 'invalid' but technically compatible fastq indexes

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM! Just confirming, no workflow input changes, correct? If so, happy to merge.

**Comment by skanwal** [comment]
@alexiswl - don't we need to wait for https://github.com/umccr/cwl-ica/pull/112 approval and merge?

**Comment by alexiswl** [comment]
> @alexiswl - don't we need to wait for https://github.com/umccr/cwl-ica/pull/112 approval and merge?

Nope, I triggered the sync already

**Comment by skanwal** [comment]
I need to understand the process better. My understanding was the sync will be triggered _after_ the PR is approved and merged into main.

**Comment by alexiswl** [comment]
> I need to understand the process better. My understanding was the sync will be triggered after the PR is approved and merged into main.

Yup but can also kick off the sync via the actions given the short timeframe

**Review by victorskl — APPROVED** [review]
Upstream https://github.com/umccr/cwl-ica/pull/112 has merged. Merging this for finalising release, next.

**Pull request merged**
