### PR TITLE
Updated templates for tn to use 4.2.4 with updated reference (prod)

### PR DESCRIPTION
**Pull request by alexiswl**
* Updated reference to v9-r3 
* Added parameters enable-cnv and enable-hrd

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Switch to DRAGEN 4.x](https://trello.com/c/ivLCfCrv/1510-portal-release-ocicat-switch-to-dragen-4x)

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
I will be rebasing this onto latest master HEAD. Hence, force push to update the branch. And resolve the conflict.

**Review by victorskl — APPROVED** [review]
Assert that

File exists
```
ica files get gds://production/reference-data/dragen_hash_tables/v9-r3/hg38-alt_masked-cnv-hla-rna/hg38-alt_masked.cnv.hla.rna-9-r3.0-1.tar.gz
```

Workflow version exists and equal to Staging
```
ica workflows versions list wfl.5830565f0858423cb49de2a1534d65c5 | grep 4.2.4--0fab721
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1699877522390719

**Review by reisingerf — APPROVED** [review]
LGTM
(Existence of workflow version and reference file in `production` verified)

**Review by ohofmann — COMMENTED** [review]
Confirmed (and note to self to add a task to pick up HRD scores in the cancer reporter)

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
