### PR TITLE
Added Spot Pricing to dev worker instance

### PR DESCRIPTION
**Pull request by alexiswl**
Additional changes:
userdata now installs IAP.
Updated to latest cdk (1.28.0)

### CODE REVIEW

**Comment by alexiswl** [comment]
@reisingerf @brainstorm LaunchTemplate now referenced inside ec2 instance. A lot of trial and error! Also put /var on an extended volume so that docker pull on a few large containers wouldn't break the entire root volume.

**Comment by brainstorm** [comment]
After adjusting the `cdk.json` a bit with my preferred parameters:

```diff
diff --git a/cdk/apps/dev_worker/cdk.json b/cdk/apps/dev_worker/cdk.json
index 5fe7a3c..c2ff2e7 100644
--- a/cdk/apps/dev_worker/cdk.json
+++ b/cdk/apps/dev_worker/cdk.json
@@ -1,13 +1,13 @@
 {
   "app": "python app.py",
   "context": {
-    "EC2_TYPE": "m4.4xlarge",
-    "KEY_NAME": "alexis-dev",
+    "EC2_TYPE": "m5a.xlarge",
+    "KEY_NAME": "romanvg",
     "MACHINE_IMAGE": "ami-0dc96254d5535925f",
     "VAR_VOLUME_SIZE": "16",
-    "EXTENDED_VOLUME_SIZE": "100",
+    "EXTENDED_VOLUME_SIZE": "80",
     "LAUNCH_TEMPLATE_NAME": "dev_worker_template",
     "INSTANCE_NAME": "dev_worker_instance_cdk",
-    "MAX_SPOT_PRICE": "0.30"
+    "MAX_SPOT_PRICE": "3"
   }
-}
```

It does not seem to like it :__/

```
$ cdk deploy
dev-worker: deploying...
dev-worker: creating CloudFormation changeset...
 0/4 | 1:42:09 PM | UPDATE_IN_PROGRESS   | AWS::CDK::Metadata        | CDKMetadata
 1/4 | 1:42:11 PM | UPDATE_COMPLETE      | AWS::CDK::Metadata        | CDKMetadata
 1/4 | 1:42:12 PM | UPDATE_IN_PROGRESS   | AWS::EC2::LaunchTemplate  | LaunchTemplate Requested update requires the creation of a new physical resource; hence creating one.
 1/4 | 1:42:14 PM | UPDATE_IN_PROGRESS   | AWS::EC2::LaunchTemplate  | LaunchTemplate Resource creation Initiated
 2/4 | 1:42:14 PM | UPDATE_COMPLETE      | AWS::EC2::LaunchTemplate  | LaunchTemplate
 3/4 | 1:42:16 PM | UPDATE_FAILED        | AWS::EC2::Instance        | dev_worker (devworker78F70816) i-03f3e7ca88d712efa does not exist
	new Instance (/private/var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/jsii-kernel-fK4auu/node_modules/@aws-cdk/aws-ec2/lib/instance.js:59:25)
	\_ /Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:49
	\_ Kernel._wrapSandboxCode (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8298:20)
	\_ Kernel._create (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:26)
	\_ Kernel.create (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7585:21)
	\_ KernelHost.processRequest (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
	\_ KernelHost.run (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
	\_ Immediate._onImmediate (/Users/romanvg/.miniconda3/envs/cdk/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
	\_ processImmediate (internal/timers.js:456:21)
 3/4 | 1:42:17 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | dev-worker The following resource(s) failed to update: [devworker78F70816].
 4/4 | 1:42:34 PM | UPDATE_COMPLETE      | AWS::EC2::LaunchTemplate  | LaunchTemplate
 4/4 | 1:42:34 PM | UPDATE_IN_PROGRESS   | AWS::CDK::Metadata        | CDKMetadata
 5/4 | 1:42:35 PM | UPDATE_COMPLETE      | AWS::EC2::Instance        | dev_worker (devworker78F70816)
 6/4 | 1:42:36 PM | UPDATE_COMPLETE      | AWS::CDK::Metadata        | CDKMetadata
 6/4 | 1:42:36 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack | dev-worker
 6/4 | 1:42:38 PM | DELETE_IN_PROGRESS   | AWS::EC2::LaunchTemplate  | LaunchTemplate
 7/4 | 1:42:39 PM | DELETE_COMPLETE      | AWS::EC2::LaunchTemplate  | LaunchTemplate
 8/4 | 1:42:40 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack | dev-worker

 ❌  dev-worker failed: Error: The stack named dev-worker is in a failed state: UPDATE_ROLLBACK_COMPLETE
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:165:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:167:7)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:152:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:172:9)
The stack named dev-worker is in a failed state: UPDATE_ROLLBACK_COMPLETE
```

**Comment by reisingerf** [comment]
If I understand correctly, you deployed and all was fine. Then you changed the parameters and re-deployed/updated the CF stack, which ended up in this error?

So the issue is with updating the stack?

**Comment by brainstorm** [comment]
No, I just changed the parameters right away without trying to deploy first... that's why I'm a bit puzzled that it is referring to some instance (i-03f3e7ca88d712efa) ... perhaps the one that Alexis launched first while building this CDK app?

**Comment by reisingerf** [comment]
If you look at the CF console, it looks like the initial create worked fine. Then an update happened, which failed. 
Perhaps a race condition... if there was already an instance, it would have to be deleted in order to create a new one with changed requirements. Or that instance has been terminated otherwise and the stack was not in sync... 

I'd try from scratch, making sure the stack does not exist first. If that's successful you could try and update...

**Comment by pdiakumis** [comment]
I do recall seeing a newly launched `dev-worker` stack with an EC2 instance from @alexiswl on Monday ~6pm (I had kicked off my own around the same time for umccrise debugging), so that might have clashed with whatever Roman was doing.

**Comment by alexiswl** [comment]
I was worried that would be an issue, if people use a different set of contexts would that resolve the issue?

**Comment by reisingerf** [comment]
If with context you mean stack name, then yes it should.
The CDK context alone would not make a difference (I think), as when you run `cdk deploy` you are deploying a CF stack and if that stack has the same name as an already existing one, you run into trouble.

And currently that stack name is hard coded (I think) here: https://github.com/umccr/infrastructure/blob/94bdc37be7b4fb94f913dc1c0932f4233ebf9fcd/cdk/apps/dev_worker/app.py#L22

We are missing a mechanism to change that, so everyone using that CDK code can create his own (independent) CF stack.

**Pull request merged**
