### PR TITLE
Upgrade stg WTS workflow to 4.2.4

### PR DESCRIPTION
**Pull request by skanwal**
- updated workflow version
- updated terraform input template

To-do:

Check reference data in `gds://staging` and copy if not available.

### CODE REVIEW

**Comment by victorskl** [comment]
* [ ] #346 must be merged and did run WTS pipeline automation in dev, first
* [ ] Check reference data in gds://staging and copy if not available.

**Comment by victorskl** [comment]
Thanks for PR, Sehrish. I will put this PR into Draft mode for now. When we complete one e2e run in Dev Portal then I will reopen to ready state and final review check, accordingly. FYI

**Comment by skanwal** [comment]
[Update Dragen transcriptome pipeline to v4.2.4](https://trello.com/c/BaSWMILf/1517-update-dragen-transcriptome-pipeline-to-v424)

**Comment by victorskl** [comment]
Scrapped ^^^ checklist.
We are pushing ahead to Staging for WGS validation set.
See https://umccr.slack.com/archives/C025TLC7D/p1694667209829749

**Review by victorskl — APPROVED** [review]
LGTM. DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
