### PR TITLE
umccrise: update stg to 2.3.1--1

### PR DESCRIPTION
**Pull request by pdiakumis**
```
ica workflows versions list wfl.714e9172f3674023b210ccc7c47db05a -a $ICA_ACCESS_TOKEN_STG | head -n2
ID                                  	NAME             	LANGUAGE	STATUS  	TIMECREATED
wfv.4c633ea9a5b94c3e8cd7bd460fe831d8	2.3.1--1--9344851	CWL     	Released	2023-09-14 09:40:12.695 +1000 AEST
```

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
Reviewing...

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update umccrise for DRAGEN 4.x](https://trello.com/c/XIlHrgZy/1511-portal-release-ocicat-update-umccrise-for-dragen-4x)

**Comment by victorskl** [comment]
We are pushing ahead to Staging for WGS validation set.
See https://umccr.slack.com/archives/C025TLC7D/p1694667209829749

**Review by victorskl — APPROVED** [review]
LGTM. DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
