### PR TITLE
Updated to use illumina reference bundle for dev

### PR DESCRIPTION
**Pull request by alexiswl**
* Changes to reference bundle for wts, somatic and qc workflows

See related discussions:

## Slack:
https://umccr.slack.com/archives/C025TLC7D/p1630373123017100

## Trello:
https://trello.com/c/9LtAq0Wg

## CWL-ICA PR:
https://github.com/umccr/cwl-ica/pull/12

## Workflows PR:
https://github.com/umccr/workflows/pull/2#issuecomment-909917533

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM! _(let me know if you wish me to apply it to DEV after merging)_

**Comment by alexiswl** [comment]
Can wait for ticks from the rest of the group on this one

**Review by skanwal — APPROVED** [review]

**Review by reisingerf — APPROVED** [review]
Happy with that!
Are we planning to harmonise the rest of the reference data as well?

**Comment by alexiswl** [comment]
The GRCh37 is there as well under `gds://development/reference-data/dragen_hash_tables/v8/GRCh37/GRCh37-cnv-anchored/` and created with the same method.  

We have umccrise and dragen_tso_ctdna both under: 

```bash
gds://development/reference-data/umccrise/
gds://development/reference-data/dragen_tso_ctdna/
```

What other reference data do we have?

**Comment by skanwal** [comment]
Think we'll need to duplicate this for prod for production workflows?

**Comment by reisingerf** [comment]
`gds://umccr-refdata-dev/somalier/sites.hg38.vcf.gz`
`gds://umccr-refdata-dev/dragen/genomes/hg38/hg38.fa`
`gds://umccr-refdata-dev/dragen/hsapiens/hg38/rnaseq/...`

Just wondering if the plan is to retire `umccr-refdata-dev` (and `umccr-refdata-prod`)

**Comment by ohofmann** [comment]
I've got this nagging suspicion that switching to the DRAGEN ref will break just about everything in umccrise. Might be one to test with @scwatts - at that point we have to make a call whether we want to use the old (bcbio) reference for a little bit longer or whether we feel confident enough to make the switch in umccrise...

**Comment by ohofmann** [comment]
Somewhat surprised this works. bcftools and other tools complain if even one ALT or patch region is named slightly differently (but those might mostly be warnings). Alright!

**Comment by alexiswl** [comment]
Terraform applied

**Pull request merged**
