### PR TITLE
Update RNAsum stg to 0.6.5

### PR DESCRIPTION
**Pull request by skanwal**
- linked to RNAsum r-package update [umccr/RNAsum@main (commits)](https://github.com/umccr/RNAsum/commits/main/)
- cwl-ica PR https://github.com/umccr/cwl-ica/pull/493
- infrastructure dev PR https://github.com/umccr/infrastructure/pull/419

### CODE REVIEW

**Comment by victorskl** [comment]
We shall discuss tomorrow team meeting for the plan rolling out this... Sehrish, okay.?

**Comment by skanwal** [comment]
Sounds good @victorskl .

**Comment by victorskl** [comment]
Let us run few cases as verification proof in Staging, @skanwal @pdiakumis meanwhile. It is better-safer SOP/practise that we do this.

We first verify ourselves with the RNAsum reports generated by new version 0.6.5.
If any fixing/improve work need, then we can go back dev and, make more updates.

If this is good, we carry on with the help of curation team signoff. 
At that point, from [ValidationSOP folder](https://drive.google.com/drive/u/3/folders/1oT19WEwd7Z8BEhiHXEzLNZ8aUFCaiKfk); we prepare `Ocicat Release Backporting Protocol 2024xxxx` change document for stakeholder sign off.  

Okay?

**Review by victorskl — APPROVED** [review]

**Comment by victorskl** [comment]
@skanwal Pls merge when you are ready. I will then follow apply the terraform.

**Comment by victorskl** [comment]
Applied to stg. We can start testing in Staging through Portal for new RNAsum-0.6.5 now.

**Pull request merged**
