### PR TITLE
Portal TF: Added SecurityHeadersPolicy to cloudfront cache behaviour

### PR DESCRIPTION
**Pull request by victorskl**

### CODE REVIEW

**Comment by victorskl** [comment]
@raylrui @williamputraintan - FYI and pls do this on any other cloudfront distribution under your watch, if any.

**Comment by victorskl** [comment]
@brainstorm This counter some aspect of Moz Observatory scanner - reported [here](https://umccr.slack.com/archives/CP356DDCH/p1720145016300259)

**Comment by brainstorm** [comment]
> @brainstorm This counter some aspect of Moz Observatory scanner - reported [here](https://umccr.slack.com/archives/CP356DDCH/p1720145016300259)

Great! Do you have a way to re-run the online scanner after those changes to see if it really mitigates all the findings? If not, merging and pushing it shouldn't introduce additional problems AFAICT, so 👍🏻

**Review by brainstorm — APPROVED** [review]

**Comment by victorskl** [comment]
> shouldn't introduce additional problems AFAICT

Yup, verifying with scanner and https://github.com/mozilla/observatory-cli

I am doing these changes very carefully; not to break UI at the same time. Balancing act.!

**Pull request merged**
