### PR TITLE
Update umccrise dev version to 2.3.0

### PR DESCRIPTION
**Pull request by alexiswl**
Update umccrise development versions to 2.30

### CODE REVIEW

**Comment by victorskl** [comment]
umccrise-2.3.0 will be backported to 2023.01 Snowshoe

**Comment by victorskl** [comment]
[Portal Release - Snowshoe: Deploy umccrise-2.3.0 to production](https://trello.com/c/xVADv8aU/1437-portal-release-snowshoe-deploy-umccrise-230-to-production)

**Review by victorskl — COMMENTED** [review]
Thank much Alexis for PR. I reckon, we also need to update to new ref data in workflow input template accordingly, yes?

Added Pete as reviewer for additional confirmation.

**Comment by victorskl** [comment]
Linking Related Upstream PRs
---

- https://github.com/umccr/umccrise/pull/123
- https://github.com/umccr/cwl-ica/pull/306

**Comment by pdiakumis** [comment]
Right, so need to change the refdata location in:

- dev (the data hasn't been copied over yet): https://github.com/umccr/infrastructure/blob/b948e2979351794abd35887f50452e627734c4d9/terraform/stacks/umccr_data_portal/workflow/template/umccrise_dev.json 
- stg: https://github.com/umccr/infrastructure/blob/b948e2979351794abd35887f50452e627734c4d9/terraform/stacks/umccr_data_portal/workflow/template/umccrise_stg.json
- prod: https://github.com/umccr/infrastructure/blob/b948e2979351794abd35887f50452e627734c4d9/terraform/stacks/umccr_data_portal/workflow/template/umccrise_prod.json

**Comment by alexiswl** [comment]
> (the data hasn't been copied over yet)

I can do that now

**Comment by alexiswl** [comment]
## Copy to development

```
gds-migrate   --src-project staging   --src-path gds://staging/reference-data/umccrise/202303/   --dest-project development   --dest-path gds://development/reference-data/umccrise/202303/
Creating the gds folder "gds://development/reference-data/umccrise/202303/"
Collecting presigned urls from source path
Uploading file /tmp/manifest.CcW.json to gds://development/reference-data/umccrise
upload: ../../../../../../tmp/manifest.CcW.json to s3://stratus-gds-aps2/1f412e89-acc8-4337-b484-08d89d4636a9/reference-data/umccrise/manifest.CcW.json
Could not get manifest presigned url, sleeping five seconds and then trying again
Uploaded manifest file of presigned urls - deleting local tmp copy
Getting AWS credentials of output folder
Populating TES task template
Launching TES task
Launching data transfer with task run "trn.64dd88cd370f49639e2f2703a1f8ce68"
Once the migration task is complete you may remove the log directory "gds://development/reference-data/umccrise/migration_logs"
```

## Copy to production

```
gds-migrate \
  --src-project staging \
  --src-path gds://staging/reference-data/umccrise/202303/ \
  --dest-project production \
  --dest-path gds://production/reference-data/umccrise/202303/
Creating the gds folder "gds://production/reference-data/umccrise/202303/"
Collecting presigned urls from source path
Uploading file /tmp/manifest.wjs.json to gds://production/reference-data/umccrise
upload: ../../../../../../tmp/manifest.wjs.json to s3://stratus-gds-aps2/11143240-789c-4320-b4e2-08d89d4636a9/reference-data/umccrise/manifest.wjs.json
Could not get manifest presigned url, sleeping five seconds and then trying again
Uploaded manifest file of presigned urls - deleting local tmp copy
Getting AWS credentials of output folder
Populating TES task template
Launching TES task
Launching data transfer with task run "trn.de338b8752c644be9f06dbd961b45def"
Once the migration task is complete you may remove the log directory "gds://production/reference-data/umccrise/migration_logs"
```

**Comment by alexiswl** [comment]
Updated genomes versions 

* dev: [5e5cdcd](https://github.com/umccr/infrastructure/pull/309/commits/5e5cdcdb217900793d50ce79b837660e890bbce6)
* stg: [7ef50d5](https://github.com/umccr/infrastructure/pull/310/commits/7ef50d5d213fbcd70dfdae10006f0d7148318ceb)
* prod: [1d62ddf](https://github.com/umccr/infrastructure/pull/311/commits/1d62ddf33df10bbbab374ad85ef78198e8c94593)

**Review by pdiakumis — APPROVED** [review]
Thank you!

**Review by victorskl — APPROVED** [review]
Thanks team! I will follow up with integration test soon. Merging...

**Comment by victorskl** [comment]
Raised this to e2e testing required.

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
