### PR TITLE
Bastion ECR TF: Created centralised Bastion ECR registry for herding container images

### PR DESCRIPTION
**Pull request by victorskl**
* Created `cttso-ica-to-pieriandx` repo

### CODE REVIEW

**Comment by victorskl** [comment]
ditto action item follow up from yesterday devops discussion

**Review by andrewpatto — APPROVED** [review]

**Comment by victorskl** [comment]
@alexiswl All good with Bastion `cttso-ica-to-pieriandx` repo?

**Comment by alexiswl** [comment]
Yes this worked great! Have logged into AWS dev on CLI and can pull the image from the bastion ECR.

**Comment by victorskl** [comment]
Cool! Thanks for confirm, Alexis. And thanks for review, Andrew. Appreciate leading/piloting this. 

Let us put this repo arrangement for now and see how this go. We shall re-drive (herding) those existing images and, build pipelines into this way, eventually.

Merging...

**Review by victorskl — COMMENTED** [review]
Cool! Thanks for confirm, Alexis. And thanks for review, Andrew. Appreciate leading/piloting this. 

Let us put image repo arrangement this way for now and see how it goes. We shall re-drive (herding) those existing images and, build pipelines into this way, eventually.

Merging...

**Pull request merged**
