### PR TITLE
Upgrade bclconvert version commit id

### PR DESCRIPTION
**Pull request by alexiswl**
Multiqc - interop fixes

Related PRs:
* https://github.com/umccr/infrastructure/pull/372
* https://github.com/umccr/infrastructure/pull/384

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
I will be rebasing this onto latest master HEAD. Hence, force push to update the branch. And resolve the conflict.

**Review by victorskl — APPROVED** [review]
Assert that


Workflow version exists and equal to Staging 
```
ica workflows versions list wfl.f257ca35ced94e648fdda1173144c476 | grep 3.7.5--6eacfb8
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1698408835779249

**Review by reisingerf — APPROVED** [review]
LGTM
(Existence of workflow version in `production` verified)

**Review by ohofmann — COMMENTED** [review]
lgtm

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
