### PR TITLE
Map fastqs now caters for WTS workflow

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Comment by alexiswl** [comment]
> @alexiswl - does any of these changes impact the script invoke command? I noticed you've updated parameters?

It might, the default --workflow-type is WGS-TUMOR-NORMAL. I've also forced consistency on parameter naming. Here's the help for the map_fastqs script help definition:

```
 ./scripts/showcase/map_fastqs.py --help
20-03-18 11:23:13 - INFO     - main                 - Getting args
usage: map_fastqs.py [-h] --fastq-csv FASTQ_CSV --tracking-sheet TRACKING_SHEET --output-dir OUTPUT_DIR [--workflow-type {WGS-TUMOR-NORMAL,WTS-TUMOR-ONLY}] [--keep-single-samples] [--keep-top-ups] [--keep-control-samples]

optional arguments:
  -h, --help            show this help message and exit
  --fastq-csv FASTQ_CSV, -i FASTQ_CSV
                        The samplesheet output from the dragen bcl convert command
  --tracking-sheet TRACKING_SHEET, -t TRACKING_SHEET
                        The metadata excel spreadsheet
  --output-dir OUTPUT_DIR, -o OUTPUT_DIR
                        The output directory which will contain a list of sub directories
  --workflow-type {WGS-TUMOR-NORMAL,WTS-TUMOR-ONLY}, -s {WGS-TUMOR-NORMAL,WTS-TUMOR-ONLY}
                        Type of data to write csv files for

  --keep-single-samples
                        Keep samples even if it is missing either the normal or tumor complement
  --keep-top-ups        Keep top-up samples
  --keep-control-samples
                        Keep control samples (those starting with NTC and PTC)
```

**Comment by alexiswl** [comment]
Here's the TES definition of the task:
```
{
    "id": "tvn.dda2a8db863046679819b84996cd53fb",
    "href": "https://aps2.platform.illumina.com/v1/tasks/tdn.d0ef6108212f476599c3af47ff87cfa0/versions/tvn.dda2a8db863046679819b84996cd53fb",
    "version": "v2-dev1",
    "description": "Given a metadata spreadsheet and a dragen file output csv, create a file list based on the sample-type ('WGS-TUMOR-NORMAL' or 'WTS'), versionId tvn.dda2a8db863046679819b84996cd53fb",
    "execution": {
        "image": {
            "name": "umccr/alpine_pandas",
            "tag": "latest-slim"
        },
        "command": "/opt/conda/bin/python",
        "args": [
            "/mnt/map_fastqs.py",
            "--fastq-csv=/data/FASTQ/fastq_list.csv",
            "--tracking-sheet=/mnt/tracking-sheet.xlsx",
            "--output-dir=/data/FASTQ/custom",
            "--workflow-type={{workflow_type}}"
        ],
        "inputs": [
            {
                "path": "/mnt/map_fastqs.py",
                "url": "https://raw.githubusercontent.com/alexiswl/umccr-infrastructure/35a979b73f224a3db392cc74bbfcb881c9177640/scripts/showcase/map_fastqs.py",
                "mode": "Download",
                "type": "File"
            },
            {
                "path": "/data/FASTQ/fastq_list.csv",
                "url": "gds://{{fastq_data_volume}}/{{fastq_data_path}}/Reports/fastq_list.csv",
                "mode": "Download",
                "type": "File"
            },
            {
                "path": "/mnt/tracking-sheet.xlsx",
                "url": "gds://umccr-refdata-dev/metadata/umccr-tracking-sheet.xlsx",
                "mode": "Download",
                "type": "File"
            }
        ],
        "outputs": [
            {
                "path": "/data/FASTQ/custom",
                "url": "gds://{{fastq_data_volume}}/{{fastq_data_path}}/FastqLists",
                "type": "Folder",
                "credentials": {}
            }
        ],
        "systemFiles": {
            "url": "{{gdsLogFolder}}",
            "credentials": {}
        },
        "environment": {
            "variables": {},
            "resources": {
                "type": "standard",
                "size": "small",
                "cpuCores": 0.0,
                "memoryGb": 0.0,
                "hardware": []
            },
            "inputStreamSettings": {
                "accessPattern": "sequential",
                "cacheSizeGB": 50,
                "blockSizeMB": 32,
                "prefetchBlocks": 32
            }
        },
        "retryLimit": 0
    },
    "acl": [
        "tid:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
        "wid:e4730533-d752-3601-b4b7-8d4d2f6373de"
    ],
    "tenantId": "YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
    "subTenantId": "wid:e4730533-d752-3601-b4b7-8d4d2f6373de",
    "createdBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
    "timeCreated": "2020-03-17T02:24:55.168915Z",
    "modifiedBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
    "timeModified": "2020-03-18T00:31:33.997724Z"
}
```

**Comment by alexiswl** [comment]
And example input json:
```
{
    "name": "fastq mapper test",
    "description": "This is a task run test of fastq-mapper, {{versionName}} ({{taskId}}, {{versionId}})",
    "arguments": {
        "fastq_data_volume": "lucattini-dev",
        "fastq_data_path": "map_fastqs/WGS_TN",
        "gdsLogFolder": "gds://lucattini-dev/map_fastqs/logs",
        "workflow_type": "WGS-TUMOR-NORMAL"
    }
}
```

**Comment by skanwal** [comment]
@alexiswl - so for the evaluation above you're using `latest-slim` and not `latest` tag? I just notice entrypoint for both are different. Which one should I use? I would like to stick to one for both fastq mapper and samplesheet split scripts.
Hope this makes sense.

**Comment by alexiswl** [comment]
> @alexiswl - so for the evaluation above you're using latest-slim and not latest tag? I just noticed entrypoint for both are different. Which one should I use? I would like to stick to one for both fastq mapper and samplesheet split scripts.
> Hope this makes sense.

I think the entrypoints by default for both of these are /opt/conda/bin/python. The latest-slim tag is derived from the latest tag. However latest-slim is restricted to using /opt/conda/bin/python as the  entrypoint. Any other entrypoint would result in a failure. I like the latest-slim as a concept but happy to go for 'latest'. The container size isn't particularly large.

**Comment by skanwal** [comment]
Last time, when I had an issue with running the `latest` tag, you had suggested to run container like `docker run -i umccr/alpine_pandas:latest /path/to/script.py`. That's why I asked if the entrypoints were different. I am trying to workout the `command` to use within TES tasks for both steps.

**Comment by alexiswl** [comment]
> Last time, when I had an issue with running the `latest` tag, you had suggested to run container like `docker run -i umccr/alpine_pandas:latest /path/to/script.py`. That's why I asked if the entrypoints were different. I am trying to workout the `command` to use within TES tasks for both steps.

Yep, so entrypoint and command in docker are different but the entrypoint in docker is synonymous with the command in TES. Personally, I don't like the 'command' or CMD usage, in docker as its ambiguous, think of it more like parameters. In this case:
```
docker run -i umccr/alpine_pandas:latest /path/to/script.py
```
the entrypoint is still `/opt/conda/bin/python` and the first parameter or CMD is `/path/to/script.py`. So for running through TES, keep the TES `command` as `/opt/conda/bin/python` and the first parameter as `/path/to/script.py` and put in additional arguments in after that.

**Comment by skanwal** [comment]
Okay - that clarifies it. Thanks.
Testing now!

**Pull request merged**
