### PR TITLE
Chore: Cognito App Client Cleanup

### PR DESCRIPTION
**Pull request by williamputraintan**
- Removal status page from the Cognito integration

### CODE REVIEW

**Review by raylrui — APPROVED** [review]

**Review by victorskl — APPROVED** [review]
Thanks! I will apply to prod in next tick.

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
@williamputraintan Can you merge this now when ready?

**Comment by williamputraintan** [comment]
> @williamputraintan Can you merge this now when ready?

Yes, merging

**Comment by victorskl** [comment]
Perhaps, I clean up too much! 😛 Thanks @reisingerf for a quick rescue effort... Appreciate help!

**Pull request merged**
