### PR TITLE
Updated bclconvert workflow

### PR DESCRIPTION
**Pull request by alexiswl**
* Override cycles matching '\w+;\w+;[nN]\d+;[nN]\d+' now auto-removes adapterread2 from samplesheet settings

---

- [ ] @victorskl to follow up apply to PROD when closing Korat milestone.

### CODE REVIEW

**Comment by victorskl** [comment]
@alexiswl I reckon this also already applied to development project bcl convert workflow, right? So that I can make validation run there.

Ideally, I wanted to run past test it in DEV and, then schedule release with Korat; if there is no urgency. Otherwise, happy to push it through PROD straight, if this is _now-now_ thing to go. Any advice?

**Comment by alexiswl** [comment]
> @alexiswl I reckon this also already applied to development project bcl convert workflow, right? So that I can make validation run there.

Yes this has been pushed to dev already

**Comment by alexiswl** [comment]
> Ideally, I wanted to run past test it in DEV and, then schedule release with Korat; if there is no urgency. Otherwise, happy to push it through PROD straight, if this is now-now thing to go. Any advice?

No immediate urgency with it since we resolved run 197 by changing the override cycles

**Comment by victorskl** [comment]
Thanks Alexis. Then, I will hold up PR & applying it to PROD for now. And, probably will do together with Korat release. 

If priority change, please kindly let me know. Happy to apply it straight, PROD.

**Review by victorskl — APPROVED** [review]
@alexiswl Happy to merge this. I note myself below to apply to PROD later.

- [ ] @victorskl to follow up apply to PROD when closing Korat milestone.

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
