### PR TITLE
Updated umccrise template and workflow version

### PR DESCRIPTION
**Pull request by alexiswl**
No longer run germline with umccrise, instead germline is run with somatic

### CODE REVIEW

**Review by pdiakumis — APPROVED** [review]
Confirming wfl id and wfl version match in staging.

**Comment by victorskl** [comment]
Holding this Release Candidate merge to Staging as waiting to line up with other tasks progress --

- PortalUI-v2.1 - improve/fix DataTable filter
- umccrise-v2.3 - woof validation comparison
- current ETA 1 more week

ditto Slack [thread details](https://umccr.slack.com/archives/CP356DDCH/p1678926764014409?thread_ts=1678580165.518959&cid=CP356DDCH) at this point-in-time

**Comment by victorskl** [comment]
I reckon, we can additionally bring along v2.3 bump as follow up commit to this PR. 

Just FYI Pete and Alexis. Let us play it by ear!

**Comment by alexiswl** [comment]
Thanks @victorskl sounds good! @pdiakumis let me know once you have a docker image ready to go for v2.3

**Review by victorskl — APPROVED** [review]
Thanks all; as finalised the `umccrise-2.3` is descoped for Snowshoe. I will be merging in tick, next.

**Comment by victorskl** [comment]
Validated in Staging. See https://umccr.slack.com/archives/CP356DDCH/p1679995526145079

**Pull request merged**
