### PR TITLE
Update RNAsum prod to 1.1.0

### PR DESCRIPTION
**Pull request by skanwal**
- linked to RNAsum r-package update [umccr/RNAsum@main (commits)](https://github.com/umccr/RNAsum/commits/main/)
- cwl-ica PR https://github.com/umccr/cwl-ica/pull/495
- infrastructure dev/stg PR  https://github.com/umccr/infrastructure/pull/425

### CODE REVIEW

**Comment by victorskl** [comment]
Status update:

- [ ] must pass and, pending e2e test verification in Portal Staging with #425

**Comment by victorskl** [comment]
UAT wait:

- [ ] https://umccr.slack.com/archives/C025TLC7D/p1717379411180859

**Comment by skanwal** [comment]
CWL workflow updated with https://github.com/umccr/cwl-ica/pull/530

**Review by victorskl — APPROVED** [review]

**Comment by victorskl** [comment]
Resolving the merge conflict...

**Comment by victorskl** [comment]
@skanwal Pls merge whenever you feel ready.
I will follow up with terraform apply.

**Pull request merged**
