### PR TITLE
Networking TF: Disabled assigning public IP by default in main-vpc

### LINKED ISSUE #432: Do not auto assign Public IP v4 for instances in main-vpc public subnet
Context:

https://aws.amazon.com/blogs/aws/new-aws-public-ipv4-address-charge-public-ip-insights/

See team discussion in threads:
- https://umccr.slack.com/archives/C02LGHE2G/p1706135975887089
- https://umccr.slack.com/archives/C02LGHE2G/p1706997530945269

Actions:
- Configure it so that it won't auto assign
- Allow on-demands assign by user

### PR DESCRIPTION
**Pull request by victorskl**
Resolves #432

### CODE REVIEW

**Review by scwatts — APPROVED** [review]
LGTM, and thanks for the discussion on this over Slack.

**Review by brainstorm — APPROVED** [review]
Fantastic!

**Comment by andrewpatto** [comment]
I mean I am sure this does what we are asking of it - so the PR is fine. I cannot comment on what services may then not work if they expect main_vpc to assign them a public IP.
(but I presume those who have knowledge of our production loads have a better knowledge of whether anything needs a public IP and is not otherwise requesting it and relying on defaults)

**Comment by victorskl** [comment]
Yup, Patto. Most production workloads are ok; I have checked them through in dev, stg and prod accounts.

I ping you in here; just to heads-up so that any implication with Elsa works in AGHA account, if leveraged this, if any.

Similar for Stephen oncoanalyser work, etc.

**Comment by andrewpatto** [comment]
No problems - there are no implications for Elsa

**Review by andrewpatto — APPROVED** [review]

**Pull request merged**
