### PR TITLE
Update prod workflow ids

### PR DESCRIPTION
**Pull request by alexiswl**
- [x] Waiting for merge of #146

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM!

**Comment by victorskl** [comment]
Btw, how urgent is this to apply PROD? Otherwise, I reckon, we stage this with next Portal release that looming around in corner...

**Comment by alexiswl** [comment]
Yep no stress, just thought it would be a good box to check for moving out of workgroups and have the workflows as represented in the project yaml as in [cwl ica](https://github.com/umccr/cwl-ica/blob/beta-release/config/project.yaml).  

Will need to also move over the dragen-germline from [cwl-iap](https://github.com/umccr-illumina/cwl-iap/blob/master/workflows/dragen-qc-hla/3.7.5--1.3.5/iap-config.yaml) to the [dragen wgs qc workflow](https://github.com/umccr/cwl-ica/blob/beta-release/workflows/dragen-wgs-qc-pipeline/3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl) too, I think @skanwal was doing that. 

Then the workflows migration from workgroups to projects is complete!!

**Comment by victorskl** [comment]
> Yep no stress,

Right, cool! `cwl-ica` is coming really good! 👍 will check-in some spare days!

> Then the workflows migration from workgroups to projects is complete!!

ah haha; this is big one! hurrah, lol

**Comment by skanwal** [comment]
> Will need to also move over the dragen-germline from cwl-iap to the dragen wgs qc workflow too, I think @skanwal was doing that.

Yep - it's under this [PR](https://github.com/umccr/infrastructure/pull/150)

**Review by reisingerf — APPROVED** [review]

**Comment by alexiswl** [comment]
@victorskl so I should put this on hold until the next portal release?

**Comment by victorskl** [comment]
That's alright @alexiswl This can be merged now. What I meant was `terraform apply`

**Pull request merged**
