### PR TITLE
Updated prod versions of workflows

### PR DESCRIPTION
**Pull request by alexiswl**
## wgs_alignment_qc:
  * Upgraded multiqc
    * See PR: https://github.com/umccr/cwl-ica/pull/83
  * Removed create-fastq-list-csv step
    * See PR: https://github.com/umccr/cwl-ica/pull/82

## wgs_tumor_normal:
  * Upgraded multiqc
    * See PR: https://github.com/umccr/cwl-ica/pull/83
  * Removed create-fastq-list-csv step
    * See PR: https://github.com/umccr/cwl-ica/pull/80

## wts_tumor_only:
  * Upgraded multiqc
    * See PR: https://github.com/umccr/cwl-ica/pull/83
  * Removed create-fastq-list-csv step
    * See PR: https://github.com/umccr/cwl-ica/pull/81

## tso_ctdna_tumor_only:
  * See PR: https://github.com/umccr/cwl-ica/pull/66
  * Restructured for v2 compatibility
  * Simplified cromwell script
  * Link fastqs into fastq directory rather than mount them in listing for demux and analysis stages of workflow

## umccrise updates
  * Updates to germline workflow affect umccrise workflow.  
  * See PR: https://github.com/umccr/cwl-ica/pull/83
  * See PR: https://github.com/umccr/cwl-ica/pull/84
  * See PR: https://github.com/umccr/cwl-ica/pull/71
  * see PR: https://github.com/umccr/cwl-ica/pull/70
 
 ---

- [ ] @victorskl to follow up apply to PROD when closing Korat milestone.

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
LGTM!

**Comment by victorskl** [comment]
Reviewing...

**Review by victorskl — APPROVED** [review]
Looking good. Just to double checking @alexiswl -- there are no changes at workflow input/output?

**Comment by alexiswl** [comment]
Yup correct no changes to workflow input / output in any workflows.

**Comment by skanwal** [comment]
@alexiswl - WTS workflow inputs has changed - we are passing reference samples and `replace-names` tsv to multiQC step?

**Comment by skanwal** [comment]
@victorskl - I'll update inputs for WTS workflow in a tick.

**Comment by alexiswl** [comment]
@victorskl this sis good to go

**Review by victorskl — COMMENTED** [review]
Awesome! Thanks both @alexiswl @skanwal 

I will perform few validation runs in DEV changes, next. 

Merging...

**Pull request merged**
