### PR TITLE
Updated templates for tn to use 4.2.4 with updated reference (dev)

### PR DESCRIPTION
**Pull request by alexiswl**
Also added in enable hrd

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Switch to DRAGEN 4.x](https://trello.com/c/ivLCfCrv/1510-portal-release-ocicat-switch-to-dragen-4x)

**Review by victorskl — APPROVED** [review]
LGTM!

---

QA steps

_(FYI Flo @reisingerf; how to - basic/blackbox verification)_

```
export AWS_PROFILE=dev
ice
```

- Assert version exists

```
ica workflows versions list wfl.a4056543ef9a474d8b16182a4e6b6c50
ID                                  	NAME 	LANGUAGE	STATUS	TIMECREATED
wfv.4e5ffa0c71e24d4aa094a89355900e14	4.2.4	CWL     	Draft 	2023-07-21 12:34:38.813 +1000 AEST
wfv.3cffcea8169b4ddc90f97389b9f1c0ff	3.9.3	CWL     	Draft 	2023-03-04 13:31:10.855 +1100 AEDT
wfv.b1c15373c5c04d809aa149235b1973bb	4.0.3	CWL     	Draft 	2022-10-04 18:32:03.244 +1100 AEDT
```

- Check workflow / pipeline name (to search in Catalogue, next)
```
ica workflows get wfl.a4056543ef9a474d8b16182a4e6b6c50 | grep name
name              dragen-somatic-with-germline-pipeline_dev-wf
```

- Go to https://github.com/umccr/cwl-ica/blob/main/cwl-ica-catalogue.md
- Browser search `dragen-somatic-with-germline-pipeline`
- .. in turn https://github.com/umccr/cwl-ica/blob/main/cwl-ica-catalogue.md#dragen-somatic-with-germline-pipeline
- .. in turn https://github.com/umccr/cwl-ica/blob/main/.github/catalogue/docs/workflows/dragen-somatic-with-germline-pipeline/4.2.4/dragen-somatic-with-germline-pipeline__4.2.4.md
- Assert that all workflow input (existing and new changes) are conformant with Automation 

...
We could Github Action script it on PR action. However. Human manual QA is also preferable. So, it is and holding that thought for now. We can do something better in OrcaBus, I suppose...

**Comment by reisingerf** [comment]
Awesome! Thanks!

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
Same here. If you'd like us to give another look, pls click "re-request review" .. then I will go through again.

Otherwise, happy for you to merge in. 

It is for dev; so not much of worry. If it breaks a thing or 2; make another PR to fix it. Rinse & spin, etc. 🙂

**Comment by alexiswl** [comment]
> how to - basic/blackbox verification)

@victorskl I forgot about this tool, [ica-check-cwl-inputs](https://github.com/umccr/ica-ica-lazy/wiki/Workflow_Handling#ica-check-cwl-inputs)

## Nest input json under 'input'
```bash
jq -r '{ "input": . }' <<< '{
  "output_file_prefix_germline": null,
  "output_file_prefix_somatic": null,
  "output_directory_germline": null,
  "output_directory_somatic": null,
  "fastq_list_rows": [],
  "tumor_fastq_list_rows": [],
  "enable_map_align_output": true,
  "enable_map_align_output_germline": false,
  "enable_duplicate_marking": true,
  "enable_sv": true,
  "enable_sv_germline": false,
  "cnv_use_somatic_vc_baf": true,
  "enable_cnv": true,
  "enable_hrd": true,
  "reference_tar": {
    "class": "File",
    "location": "gds://development/reference-data/dragen_hash_tables/v9-r3/hg38-alt_masked-cnv-hla-rna/hg38-alt_masked.cnv.hla.rna-9-r3.0-1.tar.gz"
  }
}' > input.json
```

## Run ica-check-cwl-inputs
```
ica-check-cwl-inputs --input-json input.json --ica-workflow-id wfl.a4056543ef9a474d8b16182a4e6b6c50 --ica-workflow-version-name 4.2.4
```

Gives us

```
--ica-workflow-id and --ica-workflow-version-name are defined, getting inputs from definition
Checking name attribute is present
Name value is good
Checking input is present
Ensuring that all required inputs are present:  output_directory_germline output_directory_somatic output_file_prefix_germline output_file_prefix_somatic reference_tar
Input 'reference_tar.location' is a gds file at 'gds://development/reference-data/dragen_hash_tables/v9-r3/hg38-alt_masked-cnv-hla-rna/hg38-alt_masked.cnv.hla.rna-9-r3.0-1.tar.gz' checking it's present.
Input is good
Checking engineParameters
Could not find any engine parameters, under 'engineParameters'
For future runs, I would recommend setting outputDirectory and workDirectory.
engineParameters is good
```

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Add Dragen HRD results](https://trello.com/c/3Ww9alsI/1179-portal-release-ocicat-add-dragen-hrd-results)

**Comment by victorskl** [comment]
DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
