### PR TITLE
Updated tumor normal staging input template

### PR DESCRIPTION
**Pull request by alexiswl**
Also updated the workflow id and version

### CODE REVIEW

**Review by pdiakumis — APPROVED** [review]
Confirming the wfl id and the wfl version hash in staging match.

**Comment by victorskl** [comment]
Holding this Release Candidate merge to Staging as waiting to line up with other tasks progress --

- PortalUI-v2.1 - improve/fix DataTable filter
- umccrise-v2.3 - woof validation comparison
- current ETA 1 more week

ditto Slack [thread details](https://umccr.slack.com/archives/CP356DDCH/p1678926764014409?thread_ts=1678580165.518959&cid=CP356DDCH) at this point-in-time

**Review by victorskl — APPROVED** [review]
Thanks all; will be merging in tick, next.

**Comment by victorskl** [comment]
Validated in Staging. See https://umccr.slack.com/archives/CP356DDCH/p1679995526145079

**Pull request merged**
