### PR TITLE
No longer run germline with umccrise, instead germline is run with somatic

### PR DESCRIPTION
**Pull request by alexiswl**
* Now just runs the umccrise tool instead.

* Related PRs
	* https://github.com/umccr/infrastructure/pull/284
	* https://github.com/umccr/infrastructure/pull/288

### CODE REVIEW

**Comment by victorskl** [comment]
- `e2e testing` has been done in both Dev and Staging Validation Run -- outcome `Succeeded`
- Please see Slack thread for details reporting
- https://umccr.slack.com/archives/CP356DDCH/p1679995526145079

**Review by ohofmann — APPROVED** [review]
Neat. One less thing for umccrise to handle.

**Review by victorskl — APPROVED** [review]
I have confirmed that the following exists in the production environment and accessible by ICA service account
- Workflow ID `wfl.714e9172f3674023b210ccc7c47db05a` 
- Workflow version `2.2.1--0--052b3fa`
- `ica workflows versions list wfl.714e9172f3674023b210ccc7c47db05a`


Workflow Input Template
- These changes are matched with what we validated in Staging

LGTM!

**Comment by victorskl** [comment]
Cool down period. I will merge in and apply in next ~1 hour.

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
