### PR TITLE
Update umccrise production to version 2.3.0

### PR DESCRIPTION
**Pull request by alexiswl**
## TODO 

- [x] #310

### CODE REVIEW

**Comment by victorskl** [comment]
umccrise-2.3.0 will be backported to 2023.01 Snowshoe

**Comment by victorskl** [comment]
Linking Related Upstream PRs
---

- https://github.com/umccr/umccrise/pull/123
- https://github.com/umccr/cwl-ica/pull/306

**Comment by victorskl** [comment]
- [ ] #309 integration e2e testing must pass
- [ ] #310 integration e2e testing must pass

**Comment by victorskl** [comment]
- This can now be promoted to production and ready for final PR review
- See https://umccr.slack.com/archives/CP356DDCH/p1685508793713619

**Review by victorskl — APPROVED** [review]
LGTM! 

I can verify that
- the new reference data exists in prod
- the new workflow version exists in prod
- and, accessible by ICA service user

**Comment by victorskl** [comment]
I will rebase the branch to latest from `master`.

**Review by reisingerf — APPROVED** [review]

**Review by ohofmann — APPROVED** [review]
Go ahead!

**Pull request merged**
