### PR TITLE
Update cttso pipeline workflow version (prod)

### PR DESCRIPTION
**Pull request by alexiswl**
PR for next year / Ocicat backport

See the following conversations:

## Issue
https://github.com/umccr/cwl-ica/issues/449

## PR
https://github.com/umccr/cwl-ica/pull/452
https://github.com/umccr/cwl-ica/pull/459

### CODE REVIEW

**Comment by reisingerf** [comment]
Waiting for validation in staging.

**Review by pdiakumis — APPROVED** [review]

**Comment by pdiakumis** [comment]
I meant to approve just the stg one first, sorry!

**Comment by victorskl** [comment]
Back, catching up on this.

**Comment by victorskl** [comment]
One more change request for #397 

ditto
https://umccr.slack.com/archives/CCC5J2NM6/p1706679795930429

**Review by victorskl — COMMENTED** [review]
Running Staging validation - Slack notification around https://umccr.slack.com/archives/C017F7HHWF6/p1707701656074859

**Review by victorskl — APPROVED** [review]
LGTM

**Review by pdiakumis — APPROVED** [review]
LGTM

**Review by reisingerf — APPROVED** [review]
LGTM

**Pull request merged**
