### PR TITLE
Upgrade prod WTS workflow to 4.2.4

### PR DESCRIPTION
**Pull request by skanwal**
- updated workflow version
- updated terraform input template

Data has been copied to `gds://production`

### CODE REVIEW

**Comment by victorskl** [comment]
* [ ] #347 must be merged and did run WTS pipeline automation in Staging, first
* [ ] Check reference data has been copied to `gds://production`

**Comment by skanwal** [comment]
[Update Dragen transcriptome pipeline to v4.2.4](https://trello.com/c/BaSWMILf/1517-update-dragen-transcriptome-pipeline-to-v424)

**Comment by skanwal** [comment]
Updated workflow version to reflect https://github.com/umccr/infrastructure/pull/366

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
I will be rebasing this onto latest master HEAD. Hence, force push to update the branch. And resolve the conflict.

**Review by victorskl — APPROVED** [review]
Assert that

Folder exists
```
ica folders get gds://production/reference-data/dragen_wts/multiqc/2023-07-21--4.2.4/SBJ01563
ica folders get gds://production/reference-data/dragen_wts/multiqc/2023-07-21--4.2.4/SBJ01147
ica folders get gds://production/reference-data/dragen_wts/multiqc/2023-07-21--4.2.4/SBJ01620
ica folders get gds://production/reference-data/dragen_wts/multiqc/2023-07-21--4.2.4/SBJ01286
ica folders get gds://production/reference-data/dragen_wts/multiqc/2023-07-21--4.2.4/SBJ01673
```

File exists
```
ica files get gds://production/reference-data/dragen_wts/hg38/gencode.v39.annotation.gtf
ica files get gds://production/reference-data/dragen_wts/arriba/2.4.0/cytobands_hg38_GRCh38_v2.4.0.tsv
ica files get gds://production/reference-data/dragen_wts/arriba/2.4.0/blacklist_hg38_GRCh38_v2.4.0.tsv.gz
ica files get gds://production/reference-data/dragen_wts/arriba/2.4.0/protein_domains_hg38_GRCh38_v2.4.0.gff3
ica files get gds://production/reference-data/dragen_hash_tables/v9-r3/hg38-alt_masked-cnv-hla-rna/hg38-alt_masked.cnv.hla.rna-9-r3.0-1.tar.gz
```

Workflow version exists and equal to Staging 
```
ica workflows versions list wfl.7e5ba7470b5549a6b4bf6d95daaa1214 | grep 4.2.4--4b01ed3
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1698419108081199

**Review by reisingerf — APPROVED** [review]
LGTM

**Comment by reisingerf** [comment]
(Existence of workflow version, reference files and folders in `production` verified)

**Review by ohofmann — COMMENTED** [review]
Go :)

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
