### PR TITLE
Update RNAsum prod to 0.6.5

### PR DESCRIPTION
**Pull request by skanwal**
**First wait for https://github.com/umccr/infrastructure/pull/423 to be merged**
 
- linked to RNAsum r-package update [umccr/RNAsum@main (commits)](https://github.com/umccr/RNAsum/commits/main/)
- cwl-ica PR https://github.com/umccr/cwl-ica/pull/493
- infrastructure dev PR https://github.com/umccr/infrastructure/pull/419
- infrastructure stg PR https://github.com/umccr/infrastructure/pull/423

### CODE REVIEW

**Comment by skanwal** [comment]
@pdiakumis - I have tested uploading one of the cases (SBJ02999) to the RNAsum portal and that has also worked 🎉

**Comment by victorskl** [comment]
- [ ] Staging PR #423 and validation must pass

**Comment by victorskl** [comment]
Status: this is pending validation in Staging.

Putting into draft mode for accidental merge, meanwhile.

**Comment by victorskl** [comment]
This PR is abandoned and replaced by #429

**Pull request closed without merging**
