### PR TITLE
Update RNAsum dev to 0.6.5

### PR DESCRIPTION
**Pull request by skanwal**
Linked to RNAsum r-package update https://github.com/umccr/RNAsum/commits/main/

cwl-ica PR https://github.com/umccr/cwl-ica/pull/493

### CODE REVIEW

**Comment by pdiakumis** [comment]
Just to get my head around this:

- `rnasum_wfl_version` json gets fed to ->
- rnasum_wfl_input - https://github.com/umccr/infrastructure/blob/master/terraform/stacks/umccr_data_portal/workflow/rnasum.tf#L14C3-L14C19
- which gets fed to https://github.com/umccr/infrastructure/blob/master/terraform/stacks/umccr_data_portal/workflow/rnasum.tf#L39C31-L39C47

And how does that get launched?

**Comment by victorskl** [comment]
Yes, Pete. These parameter registry being looked up by Portal workflow launching [lambdas](https://github.com/umccr/data-portal-apis/tree/dev/data_processors/pipeline/lambdas).

Trace for this particular case as follows.

RNAsum launcher:
* https://github.com/umccr/data-portal-apis/blob/7526347/data_processors/pipeline/lambdas/rnasum.py#L111

That use `SecondaryAnalysisHelper` which is inheritance from parent `IcaWorkflowHelper`
* https://github.com/umccr/data-portal-apis/blob/7526347/data_processors/pipeline/domain/workflow.py#L206
* https://github.com/umccr/data-portal-apis/blob/7526347/data_processors/pipeline/domain/workflow.py#L103


There are 3 binding contract between Portal and CWL ICA workflows: `wfl_id`, `wfl_version`, `wfl_input`. During workflow launching prep step; Portal fill few dynamic parameters along with these 3 binding parameters.

If the workflow contract arrangement here having changes then Portal Automation has to update. Especially workflow input.

HTH

**Review by pdiakumis — APPROVED** [review]
👍

**Comment by victorskl** [comment]
Sorry, will review in tick, by today.

**Review by victorskl — APPROVED** [review]
LGTM!

**Comment by victorskl** [comment]
Applied to dev

**Pull request merged**
