### PR TITLE
Upgrade dev RNAsum to 0.4.9

### PR DESCRIPTION
**Pull request by skanwal**
Linked to https://github.com/umccr/cwl-ica/pull/385 and https://github.com/umccr/cwl-ica/pull/386

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update BioInfo platform with RNAsum 0.4.8](https://trello.com/c/4x3cFDCE/1544-portal-release-ocicat-update-bioinfo-platform-with-rnasum-048)

**Comment by skanwal** [comment]
@victorskl - okay if I update exisiting PRs to point to RNAsum 0.4.9?

**Comment by victorskl** [comment]
Yes, no prob, Sehrish. 

I will re-link Trello card for completeness and, to avoid confusion as well.

**Comment by skanwal** [comment]
updating to 0.4.9

**Review by victorskl — APPROVED** [review]
LGTM. DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
