### PR TITLE
umccrise: update prod to 2.3.1--1

### PR DESCRIPTION
**Pull request by skanwal**
https://trello.com/c/XIlHrgZy/1511-portal-release-ocicat-update-umccrise-for-dragen-4x

### CODE REVIEW

**Comment by victorskl** [comment]
FYI, I have renamed it to match previous related PRs
* #362 
* #363

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update umccrise for DRAGEN 4.x](https://trello.com/c/XIlHrgZy/1511-portal-release-ocicat-update-umccrise-for-dragen-4x)

**Review by reisingerf — APPROVED** [review]

**Review by victorskl — APPROVED** [review]
Assert that


Workflow version exists and equal to Staging 
```
ica workflows versions list wfl.714e9172f3674023b210ccc7c47db05a | grep 2.3.1--1--9344851
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1699887904276999

**Review by reisingerf — APPROVED** [review]
LGTM
(Existence of workflow version in `production` verified)

**Review by ohofmann — COMMENTED** [review]
Go :)

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
