### PR TITLE
Upgrade stg RNAsum to 0.4.9

### PR DESCRIPTION
**Pull request by skanwal**
Linked to https://github.com/umccr/cwl-ica/pull/385 and https://github.com/umccr/cwl-ica/pull/386

### CODE REVIEW

**Comment by victorskl** [comment]
* [ ] #351 must be merged and did run RNAsum pipeline automation in dev, first

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update BioInfo platform with RNAsum 0.4.8](https://trello.com/c/4x3cFDCE/1544-portal-release-ocicat-update-bioinfo-platform-with-rnasum-048)

**Comment by skanwal** [comment]
Updating to 0.4.9

**Comment by victorskl** [comment]
Scrapped ^^^ checklist.
We are pushing ahead to Staging for WGS validation set.
See https://umccr.slack.com/archives/C025TLC7D/p1694667209829749

**Review by victorskl — APPROVED** [review]
LGTM. DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
