### PR TITLE
Update production tumor normal workflow id and version to also run germline tool

### PR DESCRIPTION
**Pull request by alexiswl**
Now run germline and somatic simultaneously
* Updated input template to add germline prefixes and directories
* Updated to new workflow and workflow version for production.

* Related PRS
	* https://github.com/umccr/infrastructure/pull/287
	* https://github.com/umccr/infrastructure/pull/284

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
I have confirmed that the following exists in the production environment and accessible by ICA service account
- Workflow ID `wfl.5830565f0858423cb49de2a1534d65c5` 
- Workflow version `3.9.3--e4acc1a`

Workflow Input Template
- These changes are matched with what we validated in Staging

LGTM!

**Review by ohofmann — APPROVED** [review]
Glad this made it in :)

**Comment by victorskl** [comment]
Cool down period. I will merge in and apply in next ~1 hour.

**Comment by alexiswl** [comment]
Related cwl-ica PRs:

* https://github.com/umccr/cwl-ica/pull/290
* https://github.com/umccr/cwl-ica/pull/295

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
