### PR TITLE
Portal TF: Deprecated data domain and related SSL SSM parameters

### PR DESCRIPTION
**Pull request by victorskl**
* This removes the following exported system parameters:
  ```
  /data_portal/backend/api_domain_name
  /data_portal/backend/certificate_arn
  ```
* At consumer side, these should be replaced new system parameter coordinate at:
  ```
  /data_portal/backend/api_domain_name2
  /data_portal/backend/certificate_arn2
  ```
* This will go multiple stages and this is the Phase 1 of
  https://github.com/umccr/infrastructure/issues/272

### CODE REVIEW

**Comment by victorskl** [comment]
Related https://github.com/umccr/data-portal-apis/pull/666

**Comment by victorskl** [comment]
Wait for ^^ Status Page & sscheck, at least.

**Comment by victorskl** [comment]
Going to do redirect approach and retain the ssm param for backward compatibility.

**Comment by victorskl** [comment]
Found out that Pierian accession pipeline also leverage this Portal domain name param.

https://github.com/umccr/cttso-ica-to-pieriandx/blob/main/deploy/cttso-ica-to-pieriandx-cdk/constants.ts#L22-L23

**Review by reisingerf — APPROVED** [review]

**Pull request merged**
