### PR TITLE
Update production workflow version of wts

### PR DESCRIPTION
**Pull request by alexiswl**
## Changes

* Added qualimap to dragen wts workflow

* Created dragen-wts-qc workflow for creation of qualimap and dragen outputs for QC samples

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM. Same, same from my side -- Good to go, if there is no workflow input changes required!

**Review by skanwal — APPROVED** [review]
LGTM!

**Comment by skanwal** [comment]
> Good to go, if there is no workflow input changes required!

Changes required at workflow input level were tackled in https://github.com/umccr/infrastructure/pull/243

**Comment by victorskl** [comment]
Awesome work, folks! Yes, let us keep these GitHub cross linking (PR, commit points, issue) as much as possible, please! That helps all tracing back from the release. Thank you!

**Review by victorskl — APPROVED** [review]
Awesome work, folks! 💪 Yes! Let us keep these GitHub cross inter-linking (PR, commit points, issue) going high as much as possible, please! That helps with tracing back from the release. Thank you!

**Review by victorskl — COMMENTED** [review]
Merging for release

**Comment by victorskl** [comment]
Correspondant upstream PR https://github.com/umccr/cwl-ica/pull/111

**Pull request merged**
