### PR TITLE
Updated wgs alignment qc to use version 4.2.4 (dev)

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Switch to DRAGEN 4.x](https://trello.com/c/ivLCfCrv/1510-portal-release-ocicat-switch-to-dragen-4x)

**Review by victorskl — COMMENTED** [review]
hey Alexis; reference tar accessible.

Looks like you haven't release new version yet that bears 4.2.4..?

```
ica workflows versions list wfl.ff6ca1789f4e4eb0982ea3e01407aca8
ID                                  	NAME 	LANGUAGE	STATUS	TIMECREATED
wfv.742991534f63401f9371fa15e5141168	3.9.3	CWL     	Draft 	2021-09-16 10:36:50.431 +1000 AEST
wfv.4b378a3d6460436380785ec7add25d1f	3.7.5	CWL     	Draft 	2021-06-22 10:54:20.58 +1000 AEST
```

Acknowledging that you will be 

... retiring `dragen-wgs-qc-pipeline`

https://github.com/umccr/cwl-ica/blob/main/cwl-ica-catalogue.md#dragen-wgs-qc-pipeline

... replacing with `dragen-alignment-pipeline`

https://github.com/umccr/cwl-ica/blob/main/cwl-ica-catalogue.md#dragen-alignment-pipeline

Hence, expecting you will be rotating `wfl` ID there to harmonise/reflect changes better, Right..?

No pressure..! 😅

**Comment by victorskl** [comment]
hey Alexis; just saying -- whenever you think ready, pls click "re-request review" .. then I will go through again.

**Comment by alexiswl** [comment]
> Looks like you haven't release new version yet that bears 4.2.4..?

Sorry, updated workflow id in 1956ec6 to fix this.  

```
$ ica workflows versions list "wfl.a3e19e590ed34a0fa0518718cb8a36cf"
ID                                      NAME    LANGUAGE        STATUS  TIMECREATED
wfv.8d4f7349a1c642febf1f75c8d7e1efa6    4.2.4   CWL             Draft   2023-08-03 12:01:22.186 +1000 AEST
wfv.3f2a250b212c4acc94a8f3ca61cf94bd    4.0.3   CWL             Draft   2022-10-04 16:26:32.762 +1100 AEDT
wfv.18857ca42ff347f9bb364a14796dd531    3.9.3   CWL             Draft   2021-09-16 10:34:57.832 +1000 AEST
wfv.f80bbd52779f414390701b1b7c069078    3.7.5   CWL             Draft   2021-06-17 22:04:42.754 +1000 AEST
```

**Comment by alexiswl** [comment]
Re-requested review

**Comment by victorskl** [comment]
Rope you in @reisingerf with latest trend, Flo. 

Pls note we are retiring `dragen-wgs-qc-pipeline` and `dragen-alignment-pipeline` which now accept to handle both WGS & WTS alignment QC. Hence, higher abstract `wgts_alignment_qc` type is born...

**Review by victorskl — APPROVED** [review]
LGTM!

**Comment by victorskl** [comment]
Just asking (assuming) the workflow catalogue will be updated at some point up there in cwl-ica repo, right..?

**Comment by alexiswl** [comment]
Yep, catalog updates happen on PR approvals, but wgs alignment pipeline still in https://github.com/umccr/cwl-ica/pull/383

**Comment by victorskl** [comment]
Gotcha..!

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Run WTS QC workflow through Portal before running Dragen WTS Tumor Only Workflow](https://trello.com/c/H0DQyo2B/1485-portal-release-ocicat-run-wts-qc-workflow-through-portal-before-running-dragen-wts-tumor-only-workflow)

**Comment by victorskl** [comment]
DRAGEN-4 upgrade is a go. Merging...

**Pull request merged**
