### PR TITLE
Updated tso ctdna workflow run template to version 1.2 (prod)

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: ctTSO update to 1.2](https://trello.com/c/i7gnq6pt/1509-portal-release-ocicat-cttso-update-to-12)

**Comment by victorskl** [comment]
Checklist

* [ ] #337 must be merged and did run TSO pipeline automation in Portal Staging, first

**Comment by victorskl** [comment]
Same here. ditto comment flip to [Draft](https://github.com/umccr/infrastructure/pull/337#issuecomment-1670904470) mode

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
I will be rebasing this onto latest master HEAD. Hence, force push to update the branch. And resolve the conflict.

**Review by victorskl — APPROVED** [review]
Assert that

Folder exists
```
ica folders get gds://production/reference-data/dragen_tso_ctdna/ruo-1.2.0.4/
```

File exists
```
ica files get gds://production/reference-data/dragen_tso_ctdna/ruo-1.2.0.4/test_data/run/CopyComplete.txt
```

Workflow version exists
```
ica workflows versions list wfl.230846758ccf42e3831283ab0e45af0a | grep 1.2.0--1.0.0--3473aed
```

Validation Run in Staging
- https://umccr.slack.com/archives/C017F7HHWF6/p1698695196848659

**Review by reisingerf — APPROVED** [review]
LGTM
(Existence of workflow version and reference files in `production` verified)

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
